language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

before_script:
  - export PATH=$PATH:$HOME/bin/


before_deploy :
  - ./before_deploy.sh

deploy  :
  provider: releases
  api_key: "${GITHUB_API_KEY}"
  file: "./target/roundup-generator.jar"
  skip_cleanup: true



# install:
#   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

# script:
#   - mvn -e verify deploy
#   - ./deploy/cf.sh
#   - ./deploy/deploy.sh
